apiVersion: v1
kind: Pod
metadata:
  name: test-pod-with-owner
  namespace: default
  labels:
    owner: "hoangvu"
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
