apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireOwnerLabel
metadata:
  name: require-owner-label
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    excludedNamespaces:
    - external-secrets
    - gatekeeper-system
    - argocd
    - kube-system
    - monitoring
    - argo-rollouts
